services:
  # PostgreSQL Database (start first)
  postgres:
    image: postgres:15-alpine
    env_file:
      - .env.prod
    container_name: budget-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: "${POSTGRES_DB:-budget_app}"
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-budget_app}"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 30s
    networks:
      - budget-network

  # Main application (Backend + Frontend)
  app:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      target: production
    container_name: budget-app
    restart: unless-stopped
    ports:
      - "${APP_PORT:-3001}:3001"
    environment:
      DATABASE_URL: "postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
      JWT_SECRET: "${JWT_SECRET}"
      NODE_ENV: production
      PORT: 3001
    volumes:
      - app_uploads:/app/uploads
      - app_logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - budget-network

volumes:
  postgres_data:
    driver: local
  app_uploads:
    driver: local
  app_logs:
    driver: local

networks:
  budget-network:
    driver: bridge