services:
  # Main application (Frontend + Backend)
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    container_name: budget-app
    restart: unless-stopped
    ports:
      - "${APP_PORT:-3001}:3001"
    environment:
      # Database
      DATABASE_URL: "postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
      
      # JWT & Security
      JWT_SECRET: "${JWT_SECRET}"
      
      # App Configuration
      NODE_ENV: production
      PORT: 3001
      
      # Prisma Configuration
      PRISMA_SCHEMA_ENGINE_BINARY: /app/node_modules/.prisma/client/schema-engine-debian-openssl-3.0.x
      PRISMA_QUERY_ENGINE_BINARY: /app/node_modules/.prisma/client/query-engine-debian-openssl-3.0.x
      PRISMA_FMT_BINARY: /app/node_modules/.prisma/client/prisma-fmt-debian-openssl-3.0.x
    volumes:
      - app_uploads:/app/uploads
      - app_logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - budget-network

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: budget-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: "${POSTGRES_DB:-budget_app}"
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/docker/postgres/init.sql:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-budget_app}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - budget-network

volumes:
  postgres_data:
    driver: local
  app_uploads:
    driver: local
  app_logs:
    driver: local

networks:
  budget-network:
    driver: bridge
