version: '3.8'

services:
  # PostgreSQL pour développement
  postgres:
    image: postgres:15-alpine
    container_name: budget-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: budget_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d budget_app"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis (optionnel)
  redis:
    image: redis:7-alpine
    container_name: budget-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    profiles:
      - full

volumes:
  postgres_data:
  redis_data:
